spring:
  application:
    name: lab-service
  
  profiles:
    active: dev


  # Redis Configuration
  data:
    redis:
      url: redis://default:GOwUPRpFGRVtZMSiEEWlTapCvefmpsFj@hopper.proxy.rlwy.net:11415

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update # CAUTION: validate in prod
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: false
        jdbc:
          batch_size: 50

  # Kafka Configuration
  kafka:
    bootstrap-servers: shortline.proxy.rlwy.net:57987
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      retries: 3
    consumer:
      group-id: ${spring.application.name}-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: earliest
      enable-auto-commit: false
      properties:
        spring.json.trusted.packages: "*"

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

# Cloudinary
cloudinary:
  cloud-name: du1pyzthl
  api-key: 451954261338871
  api-secret: vL9wmoZn8Yid40FtSS1irqtT3N8
  folder: medibridge/lab-reports
  secure: true

# Security (JWT Resource Server)
security:
  jwt:
    secret-key: MediBridge2026!Pr0duct1on$ecretK3y#H0sp1talManag3m3ntSyst3m@Secur1ty

# Server
server:
  port: 8085



# Actuator
management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus,info
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  health:
    db:
      enabled: true
    redis:
      enabled: true

logging:
  level:
    root: INFO
    com.medibridge: INFO
